apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}-results
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    {{- toYaml .Values.pvc.results.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.pvc.results.size }}
  storageClassName: {{ .Values.pvc.results.storageClassName | quote }}
{{- if .Values.pvc.logs.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}-logs
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    {{- toYaml .Values.pvc.logs.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.pvc.logs.size }}
  storageClassName: {{ .Values.pvc.logs.storageClassName | quote }}
{{- end }}
